version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-76-215-139.eu-west-1.compute.amazonaws.com
            database: d38cf8rfrtb4uh
            user: wwejcqidbeihrc
            password: 8b6c9fd5ac1de8d4eb1b694a6d5ed78abeb457102123e2f8c40db6c7ecb2da31
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
